// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Timeback.Infrastructure.Persistence;

#nullable disable

namespace Timeback.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TimebackDbContext))]
    [Migration("20260904121250_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Timeback.Domain.Assets.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("Timeback.Domain.Games.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiCommentary")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FinalScore")
                        .HasColumnType("integer");

                    b.Property<string>("GameTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("GameTokenHash")
                        .IsUnique();

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("Timeback.Domain.Games.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoLocked")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("EffectiveMarketDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("RequestedDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("ValuationDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "Number")
                        .IsUnique();

                    b.ToTable("rounds", (string)null);
                });

            modelBuilder.Entity("Timeback.Domain.Leaderboard.LeaderboardEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.HasIndex("Score", "CreatedAtUtc");

                    b.ToTable("leaderboard_entries", (string)null);
                });

            modelBuilder.Entity("Timeback.Domain.MarketData.DailyPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Close")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("Symbol", "Date")
                        .IsUnique();

                    b.ToTable("daily_prices", (string)null);
                });

            modelBuilder.Entity("Timeback.Domain.MarketData.InflationIndex", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Index")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateOnly>("Month")
                        .HasColumnType("date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Month")
                        .IsUnique();

                    b.ToTable("inflation_indices", (string)null);
                });

            modelBuilder.Entity("Timeback.Domain.Games.Round", b =>
                {
                    b.HasOne("Timeback.Domain.Games.Game", null)
                        .WithMany("Rounds")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Timeback.Domain.Games.RoundAllocation", "Allocations", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("RoundId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");

                            b1.Property<int>("Weight")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("RoundId");

                            b1.ToTable("round_allocations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RoundId");
                        });

                    b.OwnsOne("Timeback.Domain.Games.RoundResult", "Result", b1 =>
                        {
                            b1.Property<Guid>("RoundId");

                            b1.Property<string>("BestPossibleSymbol")
                                .IsRequired();

                            b1.Property<decimal>("BestPossibleValue");

                            b1.Property<decimal>("FinalValue");

                            b1.Property<decimal>("InflationFraction");

                            b1.Property<decimal>("MissedGain");

                            b1.Property<decimal>("NominalReturnFraction");

                            b1.Property<decimal>("RealReturnFraction");

                            b1.Property<int>("Score");

                            b1.Property<decimal>("StartingCapital");

                            b1.Property<decimal>("WorstPossibleValue");

                            b1.HasKey("RoundId");

                            b1.ToTable("rounds");

                            b1.ToJson("Result");

                            b1.WithOwner()
                                .HasForeignKey("RoundId");

                            b1.OwnsMany("Timeback.Domain.Games.RoundAssetResult", "Assets", b2 =>
                                {
                                    b2.Property<Guid>("RoundResultRoundId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<decimal>("FinalValue");

                                    b2.Property<decimal>("GrowthFactor");

                                    b2.Property<decimal>("Invested");

                                    b2.Property<string>("Symbol")
                                        .IsRequired();

                                    b2.HasKey("RoundResultRoundId", "__synthesizedOrdinal");

                                    b2.ToTable("rounds");

                                    b2.WithOwner()
                                        .HasForeignKey("RoundResultRoundId");
                                });

                            b1.Navigation("Assets");
                        });

                    b.Navigation("Allocations");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Timeback.Domain.Games.Game", b =>
                {
                    b.Navigation("Rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
